# Generated by Django 4.1.7 on 2023-02-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='eventImageOne',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='eventImageThree',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='eventImageTwo',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='user/'),
        ),
    ]
