# Generated by Django 4.1.7 on 2023-02-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventAdminApp', '0002_alter_gallery_eventimageone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='eventImageOne',
            field=models.ImageField(default=None, null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='eventImageThree',
            field=models.ImageField(default=None, null=True, upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='eventImageTwo',
            field=models.ImageField(default=None, null=True, upload_to='user/'),
        ),
    ]
