# Generated by Django 4.1.7 on 2023-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventAdminApp', '0003_images_alter_gallery_eventimageone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceImage', models.ImageField(default=None, null=True, upload_to='Services/')),
                ('eventTitle', models.CharField(max_length=300)),
            ],
        ),
    ]
