# Generated by Django 4.1.7 on 2023-03-01 03:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventAdminApp', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('eventCaption', models.CharField(max_length=200)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
